<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="im_stand_joint" type="fixed">
        <parent link="chassis"/>
        <child link="im_stand"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="im_stand">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="0.02 0.02 0.5"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.02 0.02 0.5"/>
            <geometry>
                <box size="0.02 0.02 0.5"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>