controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
       
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    
diff_cont:
  ros__parameters:

    # publish_rate: 50.0
    publish_rate: 5.0

    base_frame_id: /base_link
    # base_frame_id: odom

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_speration: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false
    # enable_odom_tf: true

  #See https://www.youtube.com/watch?v=4QKsDf1c4hc&t=854 for extra parameters
  #open_loop: false

  # wheels_per_side: x
  # wheel_seperation_multiplier: x
  # left_wheel_radius_multiplier: x
  # right_wheel_radius_multiplier: x

  # odem_frame_id: x
  # pose_covariance_diagonal: x
  # twisst_covariance_diagonal: x
  # open_loop: x
  # enable_odom_tf: x

  # cmd_vel_timeout:x
  # publish_limited_velocity: x
  # velocity_rolling_window_size: x

  # linear.x.has_velocity_limits: false
  # linear.x.has_aceleration_limits: false
  # linear.x.has_jerk_limits: false
  # linear.x.max_velocity: NAN
  # linear.x.min_velocity: NAN
  # linear.x.max_acceleration: NAN
  # linear.x.min_acceleration: NAN
  # linear.x.max_jerk: NAN
  # linear.x.min_jerk: NAN

  # angular.z.has_velocity_limits: false
  # angular.z.has_aceleration_limits: false
  # angular.z.has_jerk_limits: false
  # angular.z.max_velocity: NAN
  # angular.z.min_velocity: NAN
  # angular.z.max_acceleration: NAN
  # angular.z.min_acceleration: NAN
  # angular.z.max_jerk: NAN
  # angular.z.min_jerk: NAN

